[package]
name = "icp_summer"
version = "1.0.0"
description = ""
repository = ""
keywords = [ ]
license = "MIT"

[dependencies]
base = "0.11.1"
candb = "1.0.8"
stable-rbtree = "1.0.0"
itertools = "0.2.1"