[package]
name = "package_manager"
version = "1.0.0"
description = ""
repository = ""
keywords = [ ]
license = "MIT"

[dependencies]
env = "./env/{MOPS_ENV}"
base = "0.14.0"
itertools = "0.2.2"
assets-api = "1.0.1"
ic = "2.0.0"
sha2 = "0.1.0"
test = "2.1.0"
icrc1 = "0.0.2"