[package]
name = "package_manager"
version = "1.0.0"
description = ""
repository = ""
keywords = [ ]
license = "MIT"

[dependencies]
env = "./env/{MOPS_ENV}"
base = "0.14.0"
itertools = "0.2.2"
assets-api = "1.0.1"
ic = "2.0.0"
sha2 = "0.1.4"
test = "2.1.0"
icrc1 = "0.0.2"
icpack-lib = "./icpack-lib"
icrc1-types = "1.0.0"
account-identifier = "1.0.2"
cert = "https://github.com/nomeata/ic-certification#v0.1.3@c403ffec0a60f658a1009976c785aa567ff0da77"
icrc1-mo = "0.0.15"
icrc2-mo = "0.0.13"
icrc3-mo = "0.2.4"
icrc4-mo = "0.0.5"
ecdsa = "6.0.0"
xtended-numbers = "0.4.0"