[package]
name = "package_manager"
version = "1.0.0"
description = ""
repository = ""
keywords = [ ]
license = "MIT"

[dependencies]
env = "./env-{DFX_NETWORK}"
base = "0.14.0"
stable-rbtree = "1.0.0"
itertools = "0.2.2"
assets-api = "1.0.1"
"encoding.mo" = "https://github.com/aviate-labs/encoding.mo#master@2711d18727e954b11afc0d37945608512b5fbce2"
ordered-map = "0.2.2"
ic = "2.0.0"
sha2 = "0.1.0"
concurrent = "0.1.2"
stableheapbtreemap = "1.5.0"
test = "2.1.0"
icrc1-types = "1.0.0"