[package]
name = "indirect_caller"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.8"
ic-cdk-macros = "0.8"
candid = "0.8"
async-trait = "0.1.81"
serde = "1.0.207"
futures = "0.3.30"